version: '2'
services:
  authentication_db:
    image: sqlite:2.8.17
    ports:
      - "3001:3001"
    volumes:
      - ./db/development.sqlite3

  authentication_ms:
    build: .
    command: bash -c "bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails db:setup && rails s -p 5001 -b 0.0.0.0"
    ports:
      - "5001:5001"
    depends_on:
      - authentication_db
